### ISSUE TITLE
Handle executor payouts on Interface level in order to allow for open innovation in incentivisation models by interface devs

### ISSUE THREAD

**Issue by bytezantium** [gelatofinance/gelato#30]
implemented in #21 

It was wrong to assume that executor payouts are best generalised. 
Instead, we should allow each interface to choose their own mode of incentivising executors, just like executors on the other hand choose the interfaces they want to execute transactions from.

**Comment by hilmarx** [comment]
**Suggestions:**

I think we should still generalize the bounty payout logic in the core, as the actual process of paying it out will be the same for all interfaces. We can however make this standard payout process customizable by interface devs that may require different bounty amounts to be paid out, by making the `payBounty` function take an argument that determines the amount which will be paid out, e.g. `payBounty(uint bountyAmount)`.

This way the function can be called by interface devs (rather than coding it from scratch) with an interface specific bounty.

We should try to stick to the DRY (dont repeat yourself) mantra for future interfaces.

**Comment by bytezantium** [comment]
This issue is deprecated. We now handle all payments on the core and the core sets the parameters. This is done in context of the Centralised Execution Service Operator model.
