### ISSUE TITLE
Gelato Architecture: continuous issue

### ISSUE THREAD

**Issue by gitpusha** [gelatofinance/gelato#37]
**GELATO ARCHITECTURE: _DEPRECATED_**

**The original architecture proposal: from 1 July 2019** 
![gelato-modular-architecture](https://user-images.githubusercontent.com/36712489/61117892-d90c7500-a497-11e9-9ba2-e8b394a5a996.jpg)

**Gelato Version 1 goals: 9 July 2019**

- We always execute any ExecutionClaim in the Gelato network
- We operate our executor nodes for a **net break even** 
- Any profits from operating the executor nodes are reinvested to finance operating losses
- We make it easy for interface to be added on top of the Core Gelato protocol
- Only whitelisted interfaces can mint new ExecutionClaims
- The whitelisting of interfaces  is done after auditing by us (the core devs)
- Interface developers do not have to worry about any of the underlying execution cost logic. This is magic that we (the core protocol) handle for them. 
- Interfaces only need to fetch their respective claims prepayment fee from the core protocol when minting a new execution claim and they need to make sure they transfer that fee to the core protocol for their claim to be minted (usually interfaces will charge their end users for the fee)

**Gelato Version 1 Operating Business 9 July 2019**

We (the core devs) run a centralised Execution Service:

- only we can execute claims on the Gelato network
- we execute all claims irrespective of whether an individual claim is executed for a loss, a breakeven or a profit
- overall we should operate our service for a net break even
- we need to continually set the GelatoPrepaidFee parameter in the core protocol so that we can operate our service for a net break-even.
- all accumulated profits are pooled and kept in the Core reserve for financing of losses from claim executions

**Picture from whiteboard session on Gelato architecture goals 9 July 2019**
![Gelato-Goals](https://user-images.githubusercontent.com/36712489/61118051-36a0c180-a498-11e9-82d9-73bcbdf40828.png)

**Comment by bytezantium** [comment]
![Gelato-Goals](https://user-images.githubusercontent.com/36712489/60888008-11bd0c00-a256-11e9-9e44-312a89017846.png)

**Comment by bytezantium** [comment]
!! **CURRENT** !!

**Gelato Version 1 goals:**

- We always execute any ExecutionClaim in the Gelato network
- We operate our executor notes for a **net break even** 
- Any profits from operating the executor nodes are reinvested to finance operating losses
- We make it easy for interface to be added on top of the Core Gelato protocol
- Only whitelisted interfaces can mint new ExecutionClaims
- The whitelisting of interfaces  is done after auditing by us (the core devs)
- Interface developers do not have to worry about any of the underlying execution cost logic. This is magic that we (the core protocol) handle for them. 
- Interfaces only need to fetch their respective claims prepayment fee from the core protocol when minting a new execution claim and they need to make sure they transfer that fee to the core protocol for their claim to be minted (usually interfaces will charge their end users for the fee)

**Gelato Version 1 Operating Business**

We (the core devs) run an Execution Node:

- only we can execute claims on the Gelato network
- we execute all claims irrespective of whether an individual claim is executed for a loss, a breakeven or a profit
- overall we should operate our service for a net break even
- we need to continually set the GelatoPrepaidFee parameter in the core protocol so that we can operate our service for a net break-even.
- all accumulated profits are pooled and kept in the Core reserve for financing of losses from claim executions

**Comment by bytezantium** [comment]
**Meeting on 11 July 2019**
**Agenda: Permissioned vs. Permissionless Execution**
**Core Question discussed: Should we run a centralised Execution Service (by whitelisting our executor nodes only), or should we make execution of Gelato Claims open and permissionless**
**Outcome: We make execution permissionless BUT still always run our node to ALWAYS EXECUTE all claims in the network, EVEN FOR A LOSS.
Why?
- We do not want to be the legal operators of the Gelato Core protocol
- Probably only we will run a node anyway and thus we can steer the node execution operation towards not-for-loss operations.
- If other parties join the Execution Market, we can update and redeploy to adjust the cryptoeconomics.**

_**The Trade-Offs discussed are visualised in the whiteboard picture below**_
![Gelato-Permission-Execution-Trade-offs](https://user-images.githubusercontent.com/36712489/61116759-5f738780-a495-11e9-989d-185e522a4502.JPG)

**Comment by bytezantium** [comment]
**CURRENT REDESIGN** in #63
