### ISSUE TITLE
Final edits: canExecute() function on GelatoCore 

### ISSUE THREAD

**Issue by gitpusha** [gelatofinance/gelato#82]

**Comment by hilmarx** [comment]
Make `require(success == true` for .call obsolete, as we assume that if `canExecute()` succeeds, the actual function call should also succeed

**Comment by hilmarx** [comment]
Change the `execDepositAndSell()` & `execWithdraw()` functions in GelatoDuchX.sol so that they will accept the required variables of each claim via the payload and not via state variables (some may still require to be stored in state). For this to work, we need to change:

1) What values are encoded in the `mintClaim` func in IcedOut.sol
2) What values are stored in state in GelatoDutchX.sol
3) How these values are retrieved in the individual funcs in GelatoDutchX.sol

**Comment by hilmarx** [comment]
update contracts to solc 0.5.10 and apply gas restriction for the staticcall of the ICEDOUT contract
